### ISSUE TITLE
Support transaction

### ISSUE THREAD

**Issue by kerler** [ArangoDB-Community/arangodb-tinkerpop-provider#20]
Dear Sir,

From the below result of searching 'transaction' in source code, sounds that blueprints-arangodb-graph does not support transaction. Do you have plan to support transaction?
# 

 ArangoDBGraph.java  -  \blueprints-arangodb-graph-master\Src\Main\Java\Com\Arangodb\blueprints\
FEATURES.supportsTransactions = false;
FEATURES.supportsThreadedTransactions = false;
FEATURES.supportsThreadIsolatedTransactions = false;

 ArangoDBBatchGraph.java  -  \blueprints-arangodb-graph-master\Src\Main\Java\Com\Arangodb\blueprints\Batch\
- data into a ArangoDB graph. This is a single threaded, non-transactional bulk
  FEATURES.supportsTransactions = false;
  FEATURES.supportsThreadedTransactions = false;

**Comment by liuguoguo** [comment]
Hi Wilfried，
Any plan for this feature implementation?

**Comment by dothebart** [comment]
Hi liuguoguo, 
We're currently starting out on Spring Data; after that we may head over to blueprints again.

**Comment by liuguoguo** [comment]
Hi Wilfried,
Just want to know your current work on Spring Data, it means if "spring data for arangodb" or "spring data for any graph db which supports blueprint/gremlin". We hope more improvements in blueprints-arangodb implementation, for example, transaction support, more data types support in property, and so on. 
Thanks,
Zhiqiang

**Comment by dothebart** [comment]
Hi @liuguoguo, 
(if) its going to be an arangodb backend for spring data, so you will be able to access arangodb via spring data.

**Comment by francoisprunier** [comment]
Sharing my thoughts because I've looked into this for a customer: the way ArangoDb transactions work, plus the way the driver is written, makes this a tricky task.

ArangoDb doesn't support primitives like `begin()` or `commit()`. It only allows you to execute a bunch of javascript functions in one call. That bunch of function is executed inside a transaction _on the server_.

So, inside the tinkerpop driver, you'd have to set some sort of flag to true when calling `begin()`. That flag would be reset by `commit()` or `rollback()`. The flag is checked inside calls like `addVertex`, `updateVertex`, `addEdge` and so on: if the flag is set to true, then that call needs to be transformed to the equivalent javascript call, and put into a list. If `rollback()` is called that list is discarded, nothing happens. If `commit()` is called, then you put that list of javascript calls inside a call for a transaction and send it via the java driver.

You'd have to be very careful in the way you document this, as it won't work the way people doing SQL would expect. It would probably only support `TransactionalGraph`, not `ThreadedTransactionalGraph`

**Comment by arcanefoam** [comment]
Currently all operations are translated into AQL and executed server side. As a result all operations are atomic and transactions are not supported. Although some bridge to JavaScript is plausible, making this work is very difficult. Any operation will have to query both the db directly and the "temporal store" of uncommitted information. Another option like loading the graph into memory fails for large graphs.

The lack of transactions is a limitation of how the Java Driver works and overcoming this will result in half baked solutions.
